services:
  broker:
    image: confluentinc/cp-server:7.7.1
    hostname: broker
    container_name: topic-cleaner-broker
    ports:
      - "29092:29092"
      - "8090:8090" # REST API
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://broker:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_MIN_ISR: 1 # does not work - Can't find the min isr config for topic: __consumer_offsets using default value 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # does not help with internal topics
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1 # Replication Factor for _confluent-command topic for reasons
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1 # does not work - still waiting for _confluent-telemetry-metrics to become available
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1 # is this the right config for the telematry topic? _confluent-telemetry-metrics
      CLUSTER_ID: 'topic-cleaner-cluster'
      # KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: false # did not disable _confluent_telemetry_metrics
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092