[project]
name = "topic-cleaner"
version = "0.1.0"
description = "Playing with topic retention and compaction. Docker & Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "confluent-kafka>=2.6.0",
]
